In [1]:
def describe(x):
    print("Type:{}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))
    

In [3]:
import torch
describe(torch.Tensor(2,3)) #create a tensor with 2 rows, 3 columns

Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [4]:
describe(torch.rand(2,3))#uniform random
describe(torch.rand(2,3))#random normal

Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1144, 0.8529, 0.6214],
        [0.3426, 0.5373, 0.7541]])
Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.3745, 0.5927, 0.4650],
        [0.0279, 0.8460, 0.8849]])


In [5]:
x = torch.zeros(2,3)
describe(x)
x.fill_(1) #an in-place operation for fill it with specific values
describe(x)

Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
x = torch.Tensor([[1,2,3],
                [2,3,4]])
describe(x)#create a tensor from a list

Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [2., 3., 4.]])


In [7]:
"""
create a tensor from numpy, type: double
"""
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type:torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9928, 0.7848, 0.5853],
        [0.4930, 0.2948, 0.1953]], dtype=torch.float64)


In [8]:
x = x.long() #change tensor type
describe(x)

Type:torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [2, 3, 4]])


In [10]:
"""
tensor operation
"""
describe(torch.add(x,x))
describe(x + x)

Type:torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[2, 4, 6],
        [4, 6, 8]])
Type:torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[2, 4, 6],
        [4, 6, 8]])


In [15]:
"""
dimension base tensor operation
"""
x = torch.arange(6) #returns a 1-d tensor
describe(x)
x = x.view(2,3) #like reshape
describe(x)
describe(torch.sum(x, dim = 0)) #return 1-d row-shape tensor, every row with same column add together
describe(torch.sum(x, dim = 1))
describe(torch.transpose(x, 0, 1))#The given dimensions dim0 and dim1 are swapped.

Type:torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])
Type:torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type:torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Type:torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])
Type:torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [17]:
x = torch.arange(6).view(2,3)
describe(x)
describe(x[:1,:2]) #slice 
describe(x[1,2])#index

Type:torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type:torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type:torch.LongTensor
Shape/size: torch.Size([])
Values: 
5


In [5]:
"""
concatenating tensors
"""
import torch
x = torch.arange(6).view(2,3)
describe(torch.cat([x,x], dim = 0)) #concatenate 2 matrix in dimension 0
describe(torch.cat([x,x], dim = 1))#dimension 1
describe(torch.stack([x,x])) #stack 2 matrixs

Type:torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type:torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
Type:torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [10]:
"""
linear multiplication
"""
x1 = torch.arange(6).view(2, 3)
x1 = x1.float()
describe(x1)
x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)
describe(torch.mm(x1, x2))

Type:torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Type:torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Type:torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [16]:
"""
gradient bookkeeping
"""
x = torch.ones(2, 2, requires_grad = True)
describe(x)
print(x.grad is None)
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type:torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
Type:torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True
Type:torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


In [18]:
"""
check if nvida can use 
"""

print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

False
cpu


In [51]:
"""
Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0
remove dimension2
"""
a = torch.rand(3,3)
b = torch.unsqueeze(a, 0)
b = torch.squeeze(b,0)
describe(b)

"""
Create a random tensor of shape 5x3 in the interval [3, 7)
"""
c = 3 + torch.rand(5,3)* 4
describe(c)



Type:torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.5714, 0.3495, 0.3428],
        [0.6152, 0.9977, 0.4975],
        [0.9277, 0.9983, 0.6974]])
Type:torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[6.2998, 6.5455, 3.7869],
        [4.6558, 4.8012, 4.3980],
        [6.0963, 3.8740, 4.9034],
        [5.9983, 5.2147, 4.7035],
        [5.7375, 5.6933, 4.7876]])


In [52]:
"""
Create a tensor with values from a normal distribution (mean=0, std=1).
"""
a = torch.rand(3, 3) 
a.normal_()

tensor([[ 0.6223, -1.7477, -0.9200],
        [-0.1201,  0.5369,  1.6587],
        [-1.0105, -0.6428,  0.2986]])

In [67]:
"""
Return the batch matrix-matrix product of two 3-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).
"""
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a,b)#shape:3,4,4

c = torch.rand(3,4,5)
d = torch.rand(5,4)
torch.bmm(c, torch.unsqueeze(d,0).expand(c.size(0), *d.size()))
print(*d.size())

5 4
